name: Choose Page Test

on:
  workflow_dispatch:
    inputs:
      page:
        description: "Select page"
        type: choice
        options:
          - login
          - inventory
          - cart
          - checkout

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Playwright tests for selected page
        run: |
          echo "Testing page: ${{ github.event.inputs.page }}"
          npx playwright test --grep @${{ github.event.inputs.page }} --project=chromium    npm run test -- --page=${{ inputs.page }}
