name: choose-page-tests

on:
  workflow_dispatch:
    inputs:
      page:
        description: "Select page"
        type: choice
        options:
          - login
          - inventory
          - cart
          - checkout

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests for selected page
        run: |
          echo "Testing page: ${{ github.event.inputs.page }}"
          npx playwright test --grep @${{ github.event.inputs.page }} --project=chromium
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3