name: Tests
on:
  workflow_dispatch:
    inputs:
     name:
      description: "Name"
      type: string
      default: "test"
     age:
      description: "Age"
      type: number
      required: true

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings         
        run: echo "${{ inputs.name }}" 

      - name: Age
        run: echo "${{ inputs.age }}"
